# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import lbs_pb2 as lbs__pb2


class LocationBaseServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.put = channel.unary_unary(
        '/locationservice.LocationBaseService/put',
        request_serializer=lbs__pb2.PutRequest.SerializeToString,
        response_deserializer=lbs__pb2.Car.FromString,
        )
    self.get = channel.unary_unary(
        '/locationservice.LocationBaseService/get',
        request_serializer=lbs__pb2.GetRequest.SerializeToString,
        response_deserializer=lbs__pb2.GetResponse.FromString,
        )
    self.search = channel.unary_unary(
        '/locationservice.LocationBaseService/search',
        request_serializer=lbs__pb2.SearchRequest.SerializeToString,
        response_deserializer=lbs__pb2.SearchResponse.FromString,
        )
    self.history = channel.unary_unary(
        '/locationservice.LocationBaseService/history',
        request_serializer=lbs__pb2.HistoryRequest.SerializeToString,
        response_deserializer=lbs__pb2.Car.FromString,
        )


class LocationBaseServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def put(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def get(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def search(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def history(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_LocationBaseServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'put': grpc.unary_unary_rpc_method_handler(
          servicer.put,
          request_deserializer=lbs__pb2.PutRequest.FromString,
          response_serializer=lbs__pb2.Car.SerializeToString,
      ),
      'get': grpc.unary_unary_rpc_method_handler(
          servicer.get,
          request_deserializer=lbs__pb2.GetRequest.FromString,
          response_serializer=lbs__pb2.GetResponse.SerializeToString,
      ),
      'search': grpc.unary_unary_rpc_method_handler(
          servicer.search,
          request_deserializer=lbs__pb2.SearchRequest.FromString,
          response_serializer=lbs__pb2.SearchResponse.SerializeToString,
      ),
      'history': grpc.unary_unary_rpc_method_handler(
          servicer.history,
          request_deserializer=lbs__pb2.HistoryRequest.FromString,
          response_serializer=lbs__pb2.Car.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'locationservice.LocationBaseService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
